### ISSUE TITLE
Cascading worldgen lag.

### ISSUE THREAD

**Issue by Jomik** [oitsjustjose/Geolosys#38] opened 2017-11-26 19:57 UTC
Since Forge asks me to report this :)

> 21:55:17 | game |   | info | [20:55:17] [Server thread/WARN] [FML]: Geolosys loaded a new chunk (-28, 9  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> -- | -- | -- | -- | --
> 21:55:18 | game |   | info | [20:55:18] [Server thread/WARN] [FML]: Geolosys loaded a new chunk (-30, 16  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> 21:55:18 | game |   | info | [20:55:18] [Server thread/WARN] [FML]: Geolosys loaded a new chunk (-30, 14  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> 21:55:19 | game |   | info | [20:55:19] [Server thread/WARN] [FML]: Geolosys loaded a new chunk (-27, 2  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> 21:55:20 | game |   | info | [20:55:20] [Server thread/WARN] [FML]: Geolosys loaded a new chunk (-29, 3  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> 21:55:20 | game |   | info | [20:55:20] [Server thread/WARN] [FML]: Geolosys loaded a new chunk (-30, 1  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by oitsjustjose** [comment] 2017-11-26 21:53
Duplicate of #18, won’t fix - sorry. Disable the forge error pop up in the forge config if it bothers you.

**Closed as completed by oitsjustjose** 2017-11-26 21:53 UTC
