### ISSUE TITLE
[1.12.2] Conflict with ToroQuest Revamped

### ISSUE THREAD

**Issue by aks746** [oitsjustjose/Geolosys#293] opened 2022-01-28 12:00 UTC
- 1.12.2, Forge 2859
- Geolosys 1.12.2 3.0.10 
- [ToroQuest-Revamped](https://www.curseforge.com/minecraft/mc-mods/toroquest-revamped)-12-10-2021

If the Geolosys is installed, then the ToroQuest HUD becomes broken and shows fake villages everywhere in the world.

**Comment by oitsjustjose** [comment] 2022-01-28 13:14
Duplicate of https://github.com/oitsjustjose/Geolosys/issues/215, and unfortunately I no longer support MC 1.12.

**Closed as completed by oitsjustjose** 2022-01-28 13:14 UTC
