### ISSUE TITLE
Field Manual = Game Crash

### ISSUE THREAD

**Issue by FenrisShade** [oitsjustjose/Geolosys#111] opened 2018-05-16 10:28 UTC
## Versions:

- Minecraft Forge: forge-1.12.2-14.23.3.2689
- Geolosys: 1.12.2
- JourneyMap (optional):
- ImmersiveEngineering (optional): 1.12.2

## What happens:
When I try and open the Field Manual, Minecraft freezes and then crashes. I have tried reinstalling and reloading. Nothing thus far has fixed this. Please let me know if this is something wrong with the mod or just my pc. Thanks.

## What should happen:
Field Manual should open and Minecraft shouldn't crash.

**Comment by oitsjustjose** [comment] 2018-05-16 11:31
This would be one of those occasions where Logs are necessary.

**Comment by brisingraerowing** [comment] 2018-05-17 20:24
What version of Java are you on? The one bundled with MC (Java 8u25) is known to have a ton of issues.

**Comment by oitsjustjose** [comment] 2018-05-17 20:32
8u171 works perfectly for me.

**Comment by YanisBft** [comment] 2018-05-18 12:37
This crash also happen to me

**Comment by oitsjustjose** [comment] 2018-05-18 12:54
Can someone post the log at least?!

What language is being used, I may just have to make it crash myself >_>

**Comment by YanisBft** [comment] 2018-05-18 13:05
I don't have logs because it's not really a crash: my game just freeze indefinitely :/
I tried to open the manual in French, once with a right click and another time with a right click + Shift.

**Comment by oitsjustjose** [comment] 2018-05-20 02:17
Thanks!! I’ll look into it when I can (on a big vacation)

**Comment by oitsjustjose** [comment] 2018-05-20 16:01
This happened on Geolosys 1.9.1, but on 1.9.2 this doesn't happen for me anymore - can someone confirm?

**Comment by YanisBft** [comment] 2018-05-20 23:38
I didn't specify but this happened to me in Geolosys 1.9.2. And even in English language open the manual cause a crash.
Is it related to Java version or something like that?

**Comment by oitsjustjose** [comment] 2018-05-21 01:24
Quite Possibly. I've opened the guide in Chinese (simplified), French and English to see how it handles when book translations **are** and **aren't** available. It works fine either way; English is the fallback... so I'm genuinely confused.

**Comment by darthvader45** [comment] 2018-05-21 10:58
I'm using 1.9.2 and opened the guide in English (I haven't used any other language, can't confirm for the others), and it only freezes.  I have to crash it manually to get out of it.  WTH?

Edit:  Okay, just a work-around until this is fixed.  You mind if I make a wiki page here with the contents of the manual so that people can read it w/o having to open it?  It may be a bit inconvenient, but it should help for now.  Also, testing with java 8 u172 to see if it fixes things.  If so, advise that everyone update their java version manually, as 172 won't be auto-updated to.

**Comment by YanisBft** [comment] 2018-05-21 11:26
The crash is due to OptiFine, I just removed it from my mods and the manual works perfectly in English (where the book is translated) and also in French (where the book is not)

**Comment by darthvader45** [comment] 2018-05-21 11:28
Really now?  That's weird, no idea how Optifine would mess with this mod,
though can you pinpoint a particular setting that causes this?

Edit:  Just made an issue in the OF github.  Hopefully sp614x will take a look.

**Comment by oitsjustjose** [comment] 2018-05-21 14:12
Huh, it probably has to do with the font renderer I’m using now for the Unicode font.. closing because it’s not something I have control over — sorry all :(

**Closed as completed by oitsjustjose** 2018-05-21 14:12 UTC
Labels: bug, investigating, can't replicate

**Comment by oitsjustjose** [comment] 2018-05-21 14:16
And yes, I’ll make a plaintext wiki probably on my website or here. I’ll comment here once it’s up :)

**Comment by darthvader45** [comment] 2018-05-21 14:36
Optifine cannot support Unicode font, so reverting to your old font would honestly be better to do.  You could still keep the clean code and the custom texture, just revert the font.

Also, I think I narrowed the cause down to be potentially Optifine's Custom Font option.  @Yanis48 Try turning off the custom font option then right-clicking the manual.

**Comment by darthvader45** [comment] 2018-05-21 15:21
Okay, apparently was using D2 when the crash/freeze happened, now using D3 and even used Smooth Font to hopefully fix this issue.  If it went away, I'll remove Smooth Font to see if that did it.  If so, I'll keep it, if not, I'll remove it.

**Comment by asphaltbuffet** [comment] 2018-05-23 03:32
@darthvader45 I tried it on my environment with Custom Font option disabled and it still froze up. Only removing optifine entirely seems to prevent it so far (i haven't tried every setting yet...)

**Comment by darthvader45** [comment] 2018-05-23 19:10
As a temporary workaround (possibly), try testing it with Geolosys 1.9, the
last 1.12.2 update before the manual was changed.  That should at least
allow it to work with Optifine.

**Comment by oitsjustjose** [comment] 2018-05-27 10:29
So, since the Optifine dev is known to not give 2 craps about incompatibilities (and neither are other modders... but that's for another day), I've pushed a ["fix"](https://github.com/oitsjustjose/Geolosys/commit/22e876ae2720c79dd4d0496d3d8049a050a04a0d) that allows you to use the default font that *didn't* break the game, previously.

**Comment by YanisBft** [comment] 2018-05-27 10:45
Nice, thank you dear dev!

**Comment by darthvader45** [comment] 2018-05-27 20:29
Thank you so much, I really like the fact that you still care about us
minecrafters.  I am quite happy.  Sure, it does make it uglier (in your
opinion, imho default MC font is just fine, and gets changed via resource
pack anyways), but with a resource pack it'll still look awesome because
any book that uses the default MC font has the font changed to what the
resource pack uses, as it literally replaces the font in-game.

Golden rule in Minecraft: Never dig straight down.
