### ISSUE TITLE
[1.12.2] Charcoal Pit Compatibility

### ISSUE THREAD

**Issue by ruyanve** [oitsjustjose/Geolosys#156] opened 2018-08-20 21:05 UTC
## Versions:

- Minecraft Forge: 14.23.4.2756
- Geolosys: 2.1.1
- Charcoal Pit: 1.17

## What happens:

CharcoalPit replaces the vanilla furnace, this custom version is not able to smelt Geolosys ore clusters. Other mod ores work just fine.

## What should happen:

Clusters should smelt to ingots

## Logs (if necessary):

n/a

## Additional Comments:

We started discussing this on reddit here: https://www.reddit.com/r/feedthebeast/comments/98mzlu/charcoal_pit_has_been_updated_to_v117_fixing_some/

**Comment by oitsjustjose** [comment] 2018-08-20 23:03
Do you have UniDict installed? It messes with the Ore Dictionary and might be the cause of your problems.

It's working for me just fine in my dev environment:

![image](https://user-images.githubusercontent.com/3887324/44371190-ba7e4380-a4ab-11e8-9faf-110aa0bfe869.png)

**Comment by EnderiumSmith** [comment] 2018-08-21 10:23
Wait a bit. the clusters should NOT smelt to ingots in the furnace. That's why i replaced it.
The bloomery is what smelts them.

**Comment by oitsjustjose** [comment] 2018-08-21 13:34
That's what I had understood, so I was also confused as to what the issue was.

Closing as there isn't actually a bug (re-open it if I misunderstood what the problem was)

**Closed as completed by oitsjustjose** 2018-08-21 13:34 UTC
Labels: bug, inter-mod, can't replicate

**Comment by ruyanve** [comment] 2018-08-22 02:57
Dang, I forgot about UniDict! My bad guys, thank you for clearing this up.

Cheers <3
